name: nwd-agent # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Sends IP address and HOSTNAME of this machine to another machine # 79 char long summary
description: |
  Sends IP address and hostname info to a server of my choice, every X seconds.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

apps:
  nwd-agent:
    command: bin/nwd-agent.sh
    daemon: simple
    plugs:
      - network

parts:
  nwd-agent:
    source: .
    # See 'snapcraft plugins'
    plugin: dump
    organize:
      nwd-agent.sh: bin/nwd-agent.sh
    stage-packages:
      - curl
      - openssl
    override-prime: |
      # Fix resource permissions
      chmod +rx $CRAFT_STAGE/bin/nwd-agent.sh
      snapcraftctl prime
